# Reusable workflow to calculate coverage from codecov.io
# Workflow derived from https://github.com/nmfs-fish-tools/ghactions4r/tree/main/.github/workflows
#    and  https://github.com/inlabru-org/inlabru/blob/devel/.github/workflows/test-coverage.yaml

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: calc-coverage

jobs:
  calc-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: "https://inla.r-inla-download.org/R/testing"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"'
          extra-packages: any::covr
          needs: coverage


      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1