name: pkgcheck

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on: 
  # Manual trigger
  workflow_dispatch:
  # Run on every push to main
  push:
    branches: [main, fix-workflows]
  # Run on every PR to main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    container: ghcr.io/ropensci-review-tools/pkgcheck-action:latest
    env: 
      GITHUB_PAT: ${{ github.token }}
    steps:
      - uses: actions/checkout@v2
      - name: Run pkgcheck
        id: pkgcheck
        run: source("../Rcheck.R")  # adjust path to script here
        shell: Rscript {0}
      - uses: actions/upload-artifact@v2
        with:
          name: visual-network
          path: "${{ steps.pkgcheck.outputs.visnet_path }}"
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: "${{ steps.pkgcheck.outputs.results }}"